### ISSUE TITLE
Concept Maak het persoonlijk

### ISSUE THREAD

**Issue by PieterOlievier** [PieterOlievier/dev4-maakHetPersoonlijk-backend#1]
Voor deze opdracht zou ik graag een service maken die het mogelijk maakt om specifieke lyrics van liedjes door te sturen. Je kan een lyric opzoeken, dan geeft de app terug in welke liedjes die lyric voorkomt. Dan kan je een liedje selecteren en doorsturen. Je communiceerd dan met elkaar aan de hand van song tekst, en zo ontdek je ook nieuwe muziek. Anderzijds kan je er ook voor kiezen om zelf een berichtje te schrijven en een liedje naar keuze mee door te sturen.

Ik heb al wat opzoekingswerk gedaan naar api's die het mogelijk maken om lyrics in op te zoeken, dit heb ik gevonden. Het zou super zijn moest de ontvanger dan ook meteen het liedje kan afspelen, hier zoek ik nog iets voor.

Is dit volgens jullie een haalbaar concept?

Alvast bedant!
- Pieter

**Comment by SimonVanherweghe** [comment]
-> Je moet ons beiden ook toekennen als assignee, anders komt de issue niet op onze radar

Als er effectief API's zijn die dit mogelijk maken, dan is dit zeker haalbaar. Het afspelen kan een leuke extra zijn.

Welke stack ga je precies gebruiken? Nextjs + ...? (het hoeft niet per sé met Strapi te zijn, [alternatieven genoeg](https://jamstack.org/headless-cms/)) Check goed de criteria bij de opdracht.
